version: "3"
services:

    gitea:
        build: 
            dockerfile: Dockerfile
            context: ./
        restart: always
        volumes:
            - dbdata:/data
        ports:
            - "3000"

    drone:
        image: drone/drone
        restart: always
        depends_on: 
            - gitea
        volumes:
            - dbdata:/var/lib/drone/
        ports:
            - "8000"
            - "9000"
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=http://drone:8000
            - DRONE_SECRET=drone-workshop
            # Gitea Config
            - DRONE_GITEA=true
            - DRONE_GITEA_URL=http://gitea:3000
            - DRONE_GITEA_SKIP_VERIFY=true
            - DRONE_NETWORK=${DEFAULT_NETWORK}

    drone-agent:
        image: drone/agent
        restart: always
        depends_on:
            - drone
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=drone:9000
            - DRONE_SECRET=drone-workshop
            - DRONE_MAX_PROCS=3
    proxy:
        image: traefik
        command: --logLevel=DEBUG
        links:
            - gitea
            - drone
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./traefik/staging:/etc/traefik

volumes:
    dbdata:

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}