version: "3"
services:

    gitea:
        image: gitea/gitea:latest
        restart: always
        volumes:
            - dbdata:/data
        ports:
            - "127.0.0.1:3000:3000"
            #- "222:22"

    drone-server:
        image: drone/drone
        restart: always
        depends_on: 
            - gitea
        volumes:
            - dbdata:/var/lib/drone/
        ports:
            - 8000:8000
            - 9000:9000
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=http://drone-server:8000
            - DRONE_SECRET=drone-workshop
            # Gitea Config
            - DRONE_GITEA=true
            - DRONE_GITEA_URL=http://gitea:3000
            - DRONE_GITEA_SKIP_VERIFY=false
            - DRONE_NETWORK=${DEFAULT_NETWORK}

    drone-agent:
        image: drone/agent
        restart: always
        depends_on:
            - drone-server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=drone-server:9000
            - DRONE_SECRET=drone-workshop
            - DRONE_MAX_PROCS=3

volumes:
    dbdata:

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}